### ISSUE TITLE
Typo dans la question "Intensifier l'importation des matières premières stratégiques"

### ISSUE THREAD

**Issue by ewindels** [arnaudsm/votefinder.eu#21]
Typo dans la question "Intensifier l'importation des matières premières stratégiques"

`  "subtitle_1": "Faciliter et de coordonner les procédures d’autorisations",`
devrait être (je suppose)
`  "subtitle_1": "Faciliter et coordonner les procédures d’autorisations",`

**Comment by arnaudsm** [comment]
Merci, c'est corrigé !
